# -*- coding: utf-8 -*-
"""fetch_scroll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIuyilsVI18iZgWPLD0uD1yvJ7fXEY8i
"""

import pandas as pd

df1 = pd.read_csv('scroll_repo_list.csv')
if 'address' not in df1.columns:
    df1 = df1.rename(columns={df1.columns[0]: 'address'})
df1['amount'] = 10000

df2 = pd.read_csv('open_source_repo_list.csv')
if 'address' not in df2.columns:
    df2 = df2.rename(columns={df2.columns[0]: 'address'})
df2['amount'] = 2500

df3 = pd.read_csv('zk_paper_list.csv')
if 'address' not in df3.columns:
    df3 = df3.rename(columns={df3.columns[0]: 'address'})
df3['amount'] = 2500

df4 = pd.read_csv('hackathon_winners.csv')
if 'address' not in df4.columns:
    df4 = df4.rename(columns={df4.columns[0]: 'address'})
df4['amount'] = 2500

df5 = pd.read_csv('community_collaborators.csv')
# Check if 'address' column exists in df5
if 'address' not in df5.columns:
    # Assuming the first column is the address if 'address' column is missing
    df5 = df5.rename(columns={df5.columns[0]: 'address'})

if 'amount' in df5.columns:
    # Use provided amount if available
    df5 = df5[['address', 'amount']]
else:
    df5['amount'] = 10000  # default to 10,000 SCR
    df5 = df5[['address', 'amount']]

df6 = pd.read_csv('devcon_communities.csv')
if 'address' not in df6.columns:
    df6 = df6.rename(columns={df6.columns[0]: 'address'})
df6['amount'] = 2500

df7 = pd.read_csv('ethereum_translators.csv')
if 'address' not in df7.columns:
    df7 = df7.rename(columns={df7.columns[0]: 'address'})
df7['amount'] = 2000

# Combine all files
combined = pd.concat([df1[['address', 'amount']],
                      df2[['address', 'amount']],
                      df3[['address', 'amount']],
                      df4[['address', 'amount']],
                      df5,
                      df6[['address', 'amount']],
                      df7[['address', 'amount']]])

combined = combined.groupby('address', as_index=False)['amount'].sum()

combined.to_csv('airdrop_list.csv', index=False)
print("Final airdrop_list.csv saved!")

from google.colab import files
files.download('airdrop_list.csv')

print("Columns in df1:", df1.columns)
print("Columns in df2:", df2.columns)
print("Columns in df3:", df3.columns)
print("Columns in df4:", df4.columns)
print("Columns in df5:", df5.columns)
print("Columns in df6:", df6.columns)
print("Columns in df7:", df7.columns)